#! /usr/bin/bash
##title          : cv_install_nova_compute
##description    : Configures nova on a compute node.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# Get config info and helper functions
source /xcatpost/cv_config
source /xcatpost/cv_utils

# Main function
main(){
  # Parameters and constants
  NODE_IP=$(hostname -I| awk '{print $1}')

  package_list=(
    epel-release 
    sysfsutils
    lvm2
    targetcli
    python-oslo-db
    MySQL-python
    openstack-selinux
    openstack-utils
    openstack-nova-compute
    openstack-cinder
  )
  # install_packages ${package_list}
  setenforce 0
 
  echo "----Editing /etc/nova/nova.conf----"  
  # Set up the message broker (rabbit_mq)
  # -- NOTE: The rpc_password needs to be identical to that in the openstack controller
  openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend rabbit
  openstack-config --set /etc/nova/nova.conf DEFAULT rabbit_host  ${OPENSTACK_CONTROLLER}
  openstack-config --set /etc/nova/nova.conf DEFAULT rabbit_password ${RPC_PASS}
  
  # set up the authentication service
  # -- NOTE: The admin_password needs to be identical to that in the openstack controller
  openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
  openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_uri http://${OPENSTACK_CONTROLLER}:5000/v2.0
  openstack-config --set /etc/nova/nova.conf keystone_authtoken identity_uri http://${OPENSTACK_CONTROLLER}:35357
  openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_tenant_name services
  openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_user nova
  openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_password ${NOVA_PASS}
  openstack-config --del /etc/nova/nova.conf keystone_authtoken auth_host
  openstack-config --del /etc/nova/nova.conf keystone_authtoken auth_port
  openstack-config --del /etc/nova/nova.conf keystone_authtoken auth_protocol
  
  # configure my_ip
  openstack-config --set /etc/nova/nova.conf DEFAULT my_ip ${NODE_IP}
  
  # setup remote console access
  openstack-config --set /etc/nova/nova.conf DEFAULT vnc_enabled True
  openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_lister 0.0.0.0
  openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address ${NODE_IP}
  openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://${OPENSTACK_CONTROLLER}:6080/vnc_auto.html
  
  # configure the location of the Image service
  openstack-config --set /etc/nova/nova.conf glance host ${OPENSTACK_CONTROLLER}
  
  # enable verbose logging
  openstack-config --set /etc/nova/nova.conf DEFAULT verbose True
  echo "-----------------------------------"  
  
  # Start virtualization and nova-compute
  systemctl restart libvirtd.service openstack-nova-compute.service
  systemctl enable  libvirtd.service openstack-nova-compute.service
}


# Main script
start_logging ${LOGFILE}
print_header "$(basename $0)"
main "$@"
print_tail "$(basename $0)"


