#! /usr/bin/bash
##title          : cv_install_nova_network
##description    : Configures nova_network on a compute node.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# Get config info and helper functions
source /xcatpost/cv_config
source /xcatpost/cv_utils

# Main function
main(){
  # Parameters and constants
  read ETH1 ETH2 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -2)
  package_list=(
   openstack-nova-network
   openstack-nova-api
  )
  # install_packages ${package_list}
  
  echo "----Editing /etc/nova/nova.conf----" 
   openstack-config --set /etc/nova/nova.conf  network_api_class  nova.network.api.API
   openstack-config --set /etc/nova/nova.conf  security_group_api  nova
   openstack-config --set /etc/nova/nova.conf  firewall_driver  nova.virt.libvirt.firewall.IptablesFirewallDriver
   openstack-config --set /etc/nova/nova.conf  network_manager  nova.network.manager.FlatDHCPManager
   openstack-config --set /etc/nova/nova.conf  network_size  254
   openstack-config --set /etc/nova/nova.conf  allow_same_net_traffic  False
   openstack-config --set /etc/nova/nova.conf  multi_host  True
   openstack-config --set /etc/nova/nova.conf  send_arp_for_ha  True
   openstack-config --set /etc/nova/nova.conf  share_dhcp_address  True
   openstack-config --set /etc/nova/nova.conf  force_dhcp_release  True
   openstack-config --set /etc/nova/nova.conf  flat_network_bridge  br100
   openstack-config --set /etc/nova/nova.conf  flat_interface  ${ETH1}
   openstack-config --set /etc/nova/nova.conf  public_interface  ${ETH2}
  echo "-----------------------------------"  

  systemctl enable openstack-nova-network.service 
  systemctl start openstack-nova-network.service  
  systemctl enable openstack-nova-metadata-api.service
  systemctl start openstack-nova-metadata-api.service  
}


# Main script
# start_logging ${LOGFILE}
print_header "$(basename $0)"
main "$@"
print_tail "$(basename $0)"


