#! /usr/bin/bash
##title          : cv_install_cinder
##description    : Configures cinder on the storage node.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# Get config info and helper functions
source /xcatpost/cv_config
source /xcatpost/cv_utils

# Main function
main(){
  # Parameters and constants
  NODE_IP=$(hostname -I| awk '{print $1}')
  
  echo "---- Configuring LVM ---"
  package_list=(
  lvm2
  )
  install_packages package_list
  set -x
  systemctl enable lvm2-lvmetad.service
  systemctl start lvm2-lvmetad.service
  set +x
  
  # TODO: The name of the phys. vols. should be determined automagically
  # TODO: Do we also need to modify lvm.conf?
  # Create the LVM physical volume /dev/sdb1:
  pvcreate /dev/sdb1
  
  #Create the LVM volume group cinder-volumes:
  vgcreate cinder-volumes /dev/sdb1
  
  echo "--- Configuring OpenStack Cinder ---- "
  package_list=(
  epel-release 
  targetcli
  python-oslo-db
  MySQL-python
  openstack-utils
  openstack-cinder
  )
  install_packages package_list
  
  echo "--- Editing /etc/cinder/cinder.conf"
  set -x
  # Set up access to the backend database
  openstack-config --set /etc/cinder/cinder.conf database connection mysql://cinder:${CINDER_DBPASS}@${OPENSTACK_CONTROLLER}/cinder
  
  # Set up the message broker (rabbit_mq)
  # -- NOTE: The rpc_password needs to be identical to that in the openstack controller
  openstack-config --set /etc/cinder/cinder.conf DEFAULT rpc_backend rabbit
  openstack-config --set /etc/cinder/cinder.conf DEFAULT rabbit_host  openstack
  openstack-config --set /etc/cinder/cinder.conf DEFAULT rpc_password ${RPC_PASS}
  
  # set up the authentication service
  # -- NOTE: The admin_password needs to be identical to that in the openstack controller
  openstack-config --set /etc/cinder/cinder.conf DEFAULT auth_strategy keystone
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_uri http://${OPENSTACK_CONTROLLER}:5000/v2.0
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken identity_uri http://${OPENSTACK_CONTROLLER}:35357
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_tenant_name service
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_user cinder
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_password ${CINDER_PASS}
  openstack-config --del /etc/cinder/cinder.conf keystone_authtoken auth_host
  openstack-config --del /etc/cinder/cinder.conf keystone_authtoken auth_port
  openstack-config --del /etc/cinder/cinder.conf keystone_authtoken auth_protocol
  
  # configure my_ip
  openstack-config --set /etc/cinder/cinder.conf DEFAULT my_ip ${NODE_IP}
  
  # configure cinder to use lioadm iSCSI service
  openstack-config --set /etc/cinder/cinder.conf DEFAULT iscsi_helper lioadm
  
  # configure the location of the Image service
  openstack-config --set /etc/cinder/cinder.conf glance host ${OPENSTACK_CONTROLLER}
  
  # enable verbose logging
  openstack-config --set /etc/cinder/cinder.conf DEFAULT verbose True
  set +x
  echo "-----------------------------------"  
  
  set -x
  systemctl enable openstack-cinder-volume.service target.service
  systemctl start openstack-cinder-volume.service target.service
  set +x
}

# Main script
start_logging ${LOGFILE}
print_header "$(basename $0)"
main "$@"
print_tail "$(basename $0)"
