#! /usr/bin/bash
##title          : cv_utils
##description    : Utility functions used by installation scripts
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com


# Helper functions
start_logging(){
  logfile=$1
  touch ${LOGFILE}
  exec 1>${LOGFILE} 2>&1
}

print_header(){
  echo "######################################################"
  echo "# Running $1                                            " 
  echo "######################################################"
  echo ""
  date
}

print_tail(){
  date
  echo "---# Finished $1 #---" 
}

install_packages(){
  # Install the packages
  echo "----Installing packages----"  
  package_list=$1
  for package in ${package_list[*]}; do
    yum -y -q list installed ${package} \
    && echo "${package} is already installed" >> \
    || echo "Installing ${package}" ; yum -y install ${package}
  done
  echo "---------------------------"  
}
