#! /usr/bin/bash
##title          : cv_install_api+dash
##description    : Installs the Trinity API server, the Trinity dashboard and the xCAT web service.
##                 Please, use this script if and only if all of the above three services will be 
##                 hosted on the same server.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# The Trinity API server init script requires the Linux Standard Base
yum -y install redhat-lsb

# The Trinity API server needs python Bottle
yum -y install epel-release
yum -y install python-pip
pip install bottle

# The xCAT web service requires the following
yum install mod_ssl
service httpd restart
yum install perl-JSON

# 1. Hardcoding the directories for now
# 2. For now, assuming that the xCAT controller, OpenStack controller and the Trinity API 
#    will run on the same node

file_root=""
# Trinity API setup
cd ${file_root}/api+dash/trinity_api
python setup.py install
sed "s/127.0.0.1/$(hostname -I| awk '{print $1}')/g" /etc/trinity/trinity_api.conf > /tmp/trinity_api.conf
mv /tmp/trinity_api.conf /etc/trinity/trinity_api.conf
mkdir -p /var/log/trinity
mkdir -p /var/run/trinity

# Set up the xCAT web service
useradd trinity
echo "trinity" | passwd trinity --stdin
tabch key=xcat,username=trinity passwd.password=trinity
mkdef -t policy 6 name=trinity rule=allow

# Trinity python client setup
cd ${file_root}/api+dash/trinity_client
python setup.py install
sed "s/127.0.0.1/$(hostname -I| awk '{print $1}')/g" /etc/trinity/trinity_client.conf > /tmp/trinity_client.conf
mv /tmp/trinity_client.conf /etc/trinity/trinity_client.conf

# Trinity dashboard additions
cd ${file_root}/api+dash/trinity_dashboard
sh setup.sh

# This is to fix a bug in the httpd configuration needed for Juno
echo 'Include "/etc/httpd/conf.modules.d/*.conf"' >> /etc/httpd/conf/httpd.conf



