#! /usr/bin/bash
##title          : cv_install_api+dash
##description    : Installs the Trinity API server. You will need to edit the conf file located under /etc/trinity.
##                 and then start the API server # service trinity_api start
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# The Trinity API server init script requires the Linux Standard Base
yum -y install redhat-lsb

# The Trinity API server needs python Bottle
yum -y install epel-release
yum -y install python-pip
pip install bottle
pip install cherrypy

remote_host="controller"
remote_file_root="trinity"
remote_nfs="${remote_host}:$remote_file_root"
file_root="/tmp/${remote_file_root}"
mkdir -p ${file_root}
mount ${remote_nfs} ${file_root} 
# Trinity API setup
cd ${file_root}/api+dash/trinity_api
python setup.py install
sed "s/127.0.0.1/$(hostname -I| awk '{print $1}')/g" /etc/trinity/trinity_api.conf > /tmp/trinity_api.conf
mv /tmp/trinity_api.conf /etc/trinity/trinity_api.conf
mkdir -p /var/log/trinity
mkdir -p /var/run/trinity
umount ${file_root}

cluster="/cluster"
remote_cluster="${remote_host}:${cluster}"
mount ${remote_cluster} ${cluster}

remote_home="${remote_host}:/home"
virtual_home="/vhome"
mkdir -p ${virtual_home}
mount ${remote_home} ${virtual_home}

service trinity_api start
chkconfig trinity_api on


