#! /usr/bin/bash
##title          : cv_install_api+dash
##description    : Installs the Trinity API server. You will need to edit the conf file located under /etc/trinity.
##                 and then start the API server # service trinity_api start
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# The Trinity API server init script requires the Linux Standard Base
yum -y install redhat-lsb

# The Trinity API server needs python Bottle
yum -y install epel-release
yum -y install python-pip
pip install bottle

file_root=""
# Trinity API setup
cd ${file_root}/api+dash/trinity_api
python setup.py install
sed "s/127.0.0.1/$(hostname -I| awk '{print $1}')/g" /etc/trinity/trinity_api.conf > /tmp/trinity_api.conf
mv /tmp/trinity_api.conf /etc/trinity/trinity_api.conf
mkdir -p /var/log/trinity
mkdir -p /var/run/trinity

