#! /usr/bin/bash
##title          : cv_install_xcatws
##description    : Setups the xCAT web service.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# The xCAT web service requires the following
yum -y install mod_ssl
service httpd restart
yum -y install perl-JSON

# Set up the xCAT web service
useradd trinity
echo "trinity" | passwd trinity --stdin
source /etc/profile.d/xcat.sh
tabch key=xcat,username=trinity passwd.password=trinity
mkdef -t policy 6 name=trinity rule=allow

# Fix permissions in the httpd.conf file
sed  -e "/<Directory \/>/,/<\/Directory>/ s/Require/#Require/" -i httpd.conf
service httpd restart
