#! /usr/bin/bash
##title          : cv_fly_clusterbats
##description    : Automatically test controller installation and deploys the cluster. 
##                 You need to edit the params file in /trinity/testing. (to be writter)
##author         : Themis Athanassiadou
##email          : themis.athanassiadou@clustervision.com

if [ ! -x bats ]; then
    cd /tmp
    bash /trinity/testing/install_bats.sh
    cd -
fi

source /etc/profile.d/xcat.sh

exec &> >(tee -a "/var/log/bats.log")

bats /trinity/testing/clusterbats/t*.bats 
if [[ -d /trinity/testing/clusterbugs ]]; then
    bats /trinity/testing/clusterbugs/*.bats
fi 

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
