#!/bin/bash
ip link set docker0 down 2>/dev/null|| true
brctl delbr docker0 2>/dev/null || true

# Determine our container name
NAME=$(hostname -s | sed s/node/c/)

while : ; do 
    # Determine in which virtual cluster this node is active
    for VC in $(ls /cluster | grep "^vc-"); do
        if host $NAME.$VC > /dev/null 2>&1 ; then found=1; break; fi
    done

    if [ -z "$found" ]; then
        sleep 60
        continue;
    fi

    IP=$(gethostip -d ${NAME}.${VC})
    GW=$(gethostip -d gateway.${VC} 2>/dev/null || gethostip -d login.${VC})
 
    # Check a few directories and files
    if [ ! -d /cluster/${VC} ]; then
        sleep 5
        continue;
    fi
    
    if ! ping -c 5 -W 5 login.${VC} >/dev/null 2>&1 ; then
        sleep 60
        continue;
    fi
    # All tests succeeded, just get on with it.
    break;
done


# check if there is a cluster specific image
if wget http://controller:5050/v1/repositories/library/${VC}/tags -q -O-; then
   IMAGE=${VC}
else
   IMAGE=trinity
fi

# check if we have infiniband
if [ "$(ls -A /sys/class/infiniband)" ]; then
    IB_DEVICES=$(find /dev/infiniband -printf "--device=%p ")
else
    IB_DEVICES=""
fi

# check if we have infiniband
if [ -e /dev/ipath ]; then
    IPATH=$(find /dev/ipath -printf "--device=%p ")
else
    IPATH=""
fi

# Check if we want to inject files into the container
if [ -d "/trinity/site-local/container/files" ]; then
    INJECT=$(find /trinity/site-local/container/files -type f -printf "-v %p:/%P ")
fi

# determine the ethernet device name
# Fix for 229
ETH1=$(ip route | grep default | awk '{print $5}' | head -1)

state=$(docker inspect --format='{{.State.Running}}' trinity)
case $state in
    true)
        ;;
    false)
        docker start trinity
        /usr/local/sbin/pipework ${ETH1} trinity ${IP}/16@${GW}
        ;;
    *)
        docker run \
           --net=none \
           ${IB_DEVICES} \
           ${IPATH} \
           -v /root:/root \
           -v /trinity/clustervision:/trinity/clustervision \
           -v /home/${VC}:/home \
           -v /cluster/${VC}:/cluster \
           -v /cluster/${VC}/etc/slurm:/etc/slurm \
           -v /cluster/${VC}/etc/munge:/etc/munge \
           -v /cluster/${VC}/.modulespath:/usr/share/Modules/init/.modulespath \
           ${INJECT} \
           --hostname=${NAME}.${VC} \
           --dns-search=${VC} \
           --name=trinity \
           -d controller:5050/${IMAGE}
        /usr/local/sbin/pipework ${ETH1} trinity ${IP}/16@${GW}
    ;;
esac
