#! /usr/bin/bash
#title		: cv_install_rsa
#description	: Installs the monitoring service from OMD on the monitoring server
#author		: Abhishek Mukherjee
#email		: abhishek.mukherjee@clustervision.com

yum install -y epel-release 
yum install -y wget telnet net-tools
# This is a temporary measure 
# The rpm should either be in the local repo 
# or we should make sure that we download a consistent version of the rpm
wget http://files.omdistro.org/releases/centos_rhel/omd-1.20.rhel7.x86_64.rpm
yum install -y --nogpgcheck omd-1.20.rhel7.x86_64.rpm
omd create monitoring
omd config monitoring set DEFAULT_GUI check_mk
omd config monitoring set APACHE_TCP_PORT 5003
omd config monitoring set APACHE_TCP_ADDR $(hostname -I | awk '{print $1}')
su - monitoring -c "htpasswd -b ~/etc/htpasswd admin system"
su - monitoring -c "htpasswd -D ~/etc/htpasswd omdadmin"
site="monitoring"
sites="/omd/sites"
check_mk="${sites}/${site}/etc/check_mk"
mul_wato="${check_mk}/multisite.d/wato"
users="${mul_wato}/users.mk"
cat >> ${users} << EOF

# Create the admin user
multisite_users.update(
{'admin': {'alias': u'admin',
              'locked': False,
              'roles': ['admin']}}
)

EOF
chown monitoring:monitoring ${users}
omd start monitoring
echo "$0 finished" >> /var/log/postinstall.log

