#! /usr/bin/bash
##title          : cv_install_login
##description    : Installs the Trinity login node creation tool, tlntool.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

remote_host="controller"
remote_file_root="/trinity"
remote_nfs="${remote_host}:$remote_file_root"
file_root="/tmp${remote_file_root}"
mkdir -p ${file_root}
mount ${remote_nfs} ${file_root} 
# Trinity login setup
cd ${file_root}/trinity_login/
cp etc/trinity/login.conf /etc/trinity/login.conf
cp usr/bin/tlntool /usr/bin/tlntool
chmod uga+x /usr/bin/tlntool
cd /
umount ${file_root}
echo "$0 finished" >> /var/log/postinstall.log

