#!/usr/bin/env bash
##title          : cv_build_master_login_image
##description    : Builds the login image on the master
##author         : Hans Then
##email          : hans.then@clustervision.com

LOGIN_IMG=/trinity/qcows/login.qcow2
SLURM_RPMS=$(echo -n /root/rpms/; ls -m /trinity/login/rpms/ | sed -e 's#,#,/root/rpms/#g' | tr -d '\n')

yum -y -q install guestfish
export LIBGUESTFS_BACKEND=direct
mkdir -p /trinity/qcows/
wget -c http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2 -P /trinity/qcows/
rm ${LOGIN_IMG} 2> /dev/null
cp /trinity/qcows/CentOS-7-x86_64-GenericCloud.qcow2 ${LOGIN_IMG}

virt-copy-in -a ${LOGIN_IMG} /trinity/login/rpms/ /root 
virt-customize -a ${LOGIN_IMG} \
    --root-password password:system \
    --hostname login \
    --timezone UTC \
    --install epel-release \
    --install ntp \
    --edit "/etc/ntp.conf: s/^server/#server/" \
    --run-command "systemctl enable ntpd" \
    --run-command "echo 'server 10.141.255.254  prefer' >> /etc/ntp.conf" \
    --run-command "groupadd -g 1001 slurm" \
    --run-command "useradd -u 1001 -g 1001 -d /var/run/slurm -s /sbin/nologin slurm" \
    --run-command "groupadd -g 1002 munge" \
    --run-command "useradd -u 1002 -g 1002 -d /var/run/munge -s /sbin/nologin munge" \
    --install munge,munge-libs,gcc,vim-enhanced \
    --install readline-devel,openssl-devel,perl-ExtUtils-MakeMaker,perl-Switch,pam-devel \
    --install ${SLURM_RPMS} \
    --delete /etc/slurm \
    --link /cluster/etc/slurm:/etc/slurm \
    --mkdir /var/log/slurm \
    --run-command "chown -R slurm:slurm /var/log/slurm" \
    --run-command "systemctl enable slurm munge" \
    --edit "/etc/ssh/sshd_config: s/[#]*PasswordAuthentication no/PasswordAuthentication yes/g" \
    --edit "/etc/sysconfig/network-scripts/ifcfg-eth0: s/^PEERDNS=.*/PEERDNS=\"no\"/g" \
    --install oddjob-mkhomedir,nss-pam-ldapd,authconfig \
    --edit "/etc/oddjobd.conf.d/oddjobd-mkhomedir.conf: s/0022/0077/g" \
    --run-command "authconfig --enablemkhomedir --update" \
    --run-command "systemctl enable oddjobd" \
    --install openldap,openldap-clients,openldap-servers \
    --mkdir /cluster \
    --mkdir /home \
    --edit "/etc/selinux/config: s/SELINUX=enforcing/SELINUX=permissive/" \
    --run-command "authconfig --enablemkhomedir --update" \
    --install environment-modules,whatsup \
    --delete /usr/share/Modules/init/.modulespath \
    --link /cluster/.modulespath:/usr/share/Modules/init/.modulespath \
    --install python-ldap,python-retrying,xorg-x11-xauth,bind-utils,python-pip,git,jq,traceroute,tcpdump
                               
virt-copy-in -a ${LOGIN_IMG} /trinity/login/rootimg/* /

# Diagnostics
virt-cat -a ${LOGIN_IMG} /etc/ssh/sshd_config | grep PasswordAuthentication
virt-cat -a ${LOGIN_IMG} /etc/sysconfig/network-scripts/ifcfg-eth0
