#!/usr/bin/env bash
##title          : cv_build_master_registry
##description    : Sets up all docker containers on master
##                 The following services are dockerized
##                   MariaDB (Database)
##                   RabbitMQ (Message Queue)
##                   Keystone (OpenStack Identity)
##                   Glance (OpenStack Image)
##                   Nova controller (OpenStack Compute: controller part)
##                   omd (Online Monitoring Distribution)
##                   trinity (The trinity compute node image)
##author         : Hans Then
##email          : hans.then@clustervision.com

#------------------------------------------------------------------------------
# Setup the dockerized components
#------------------------------------------------------------------------------

REGISTRY="localhost:5050"
TOPDIR="/trinity"
profiles=(
  "openldap"
  "mariadb"
  "galera"
  "rabbitmq"
  "keystone"
  "glance"
  "nova_controller"        
  "omd"
  "trinity"
)

keystone_endpoint="http://$(hostname -i):35357/v2.0"

for profile in "${profiles[@]}"; do
  docker build --rm=true -t ${REGISTRY}/${profile} ${TOPDIR}/${profile}
  docker push ${REGISTRY}/${profile}
done
