#! /usr/bin/bash
##title          : cv_conserver
##description    : Setup conserver
##author         : Hans Then 
##email          : hans.then@clustervision

source /etc/profile.d/xcat.sh
if [[ $(nodels compute | wc -l ) = 0 ]]; then
   echo "No nodes found, exiting"
   exit 1
fi
chtab node=compute nodehm.serialport=0 nodehm.serialspeed=19200 nodehm.serialflow=hard
makeconservercf
systemctl start conserver
chtab node=compute nodehm.serialport="" nodehm.serialspeed="" nodehm.serialflow=""

echo "$0 finished" >> /var/log/postinstall.log

