#!/bin/bash

set -x
if [ ! ping -c 5 "syndir.clustervision.com" > /dev/null 2>&1 ]; then
cat > /etc/openldap/cv_clustervision.conf << EOF
moduleload back_ldap.la
database        ldap

suffix          "dc=syndir,dc=clustervision,dc=com"
uri             ldap://syndir.clustervision.com
binddn          "uid=readonly,cn=users,dc=syndir,dc=clustervision,dc=com"
bindpw          "TbQ7GHnG"

rootdn "cn=Manager,dc=syndir,dc=clustervision,dc=com"
rootpw {SSHA}QXcoGwQHTHSRtLfP5QfGqICYA9sHHOJJ
EOF
fi 

echo $PROFILE
if [ "$PROFILE" == controller ]; then
cat > /etc/openldap/slapd.conf << EOF
include         /etc/openldap/schema/core.schema
include         /etc/openldap/schema/cosine.schema
include         /etc/openldap/schema/inetorgperson.schema
include         /etc/openldap/schema/trinity.schema
include         /etc/openldap/schema/nis.schema

pidfile         /var/run/openldap/slapd.pid

include         /etc/openldap/cv_local.conf
include 	/etc/openldap/cv_clustervision.conf

moduleload back_meta.la
database        meta
suffix          "dc=cluster"

rootdn "cn=Manager,dc=cluster"
rootpw {SSHA}QXcoGwQHTHSRtLfP5QfGqICYA9sHHOJJ

uri             "ldap://controller/dc=local,dc=cluster"
suffixmassage   "dc=local,dc=cluster" "dc=local"

uri             "ldap://controller/dc=syndir,dc=cluster"
suffixmassage   "dc=syndir,dc=cluster" "dc=syndir,dc=clustervision,dc=com"
EOF

cat > /etc/openldap/cv_clustervision.conf << EOF
moduleload back_ldap.la
database        ldap

suffix          "dc=syndir,dc=clustervision,dc=com"
uri             ldap://syndir.clustervision.com
binddn          "uid=readonly,cn=users,dc=syndir,dc=clustervision,dc=com"
bindpw          "TbQ7GHnG"

rootdn "cn=Manager,dc=syndir,dc=clustervision,dc=com"
rootpw {SSHA}QXcoGwQHTHSRtLfP5QfGqICYA9sHHOJJ
EOF

systemctl restart slapd
fi
