#! /usr/bin/bash
#title		: cv_cleanup_netorking
#description	: Docker by default create various networking customizations
#                 which we do not use on the Trinity nodes; we use pipework for
#                 that purpose. This script will remove all the these customizations  
#author		: Abhishek Mukherjee
#email		: abhishek.mukherjee@clustervision.com

#-- disable the docker bridge
ip link set docker0 down || true
ip link delete docker0 type bridge || true
#-- flush iptable rules created by Docker 
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X
iptables -t security -F
iptables -t security -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

