#! /usr/bin/bash
##title          : cv_fly_clusterbats
##description    : Automatically test controller installation and deploys the cluster. 
##                 You need to edit the params file in /trinity/testing. (to be writter)
##author         : Themis Athanassiadou
##email          : themis.athanassiadou@clustervision.com

if [ ! -d /trinity/testing/bats ]; then
    yum -y -q install git
    git clone https://github.com/sstephenson/bats.git && bats/install.sh /usr/local
fi

exec &> >(tee -a "/var/log/bats.log")

#------------------------------------------
# Run the controller bats for test case 1.1
#-------------------------------------------
bats /trinity/testing/clusterbats/t1.1.bats 
bats /trinity/testing/clusterbats/t1.2.bats
bats /trinity/testing/clusterbats/run_mpi.bats 
