#! /usr/bin/bash
##description    : The third round of High Availability.
##                 This will setup:
##                 1. Pacemaker configuration for the OpenStack Controller services
##                 This needs to be called after cv_install_dockerize.
##author         : Hans Then
##email          : hans.then@clustervision

# Setup high availability for the docker containers
pcs resource create docker systemd:docker op monitor interval="37s"
pcs resource clone docker clone-node-max=1 notify=false

pcs resource create mariadb systemd:mariadb op monitor interval="37s"
pcs resource create rabbitmq systemd:rabbitmq op monitor interval="37s"
pcs resource create keystone systemd:keystone op monitor interval="37s"
pcs resource create glance systemd:glance op monitor interval="37s"
pcs resource create nova-controller systemd:nova-controller op monitor interval="37s"

pcs resource group add grp_OpenStack mariadb rabbitmq keystone glance nova-controller
pcs constraint colocation add grp_OpenStack ip
pcs constraint order start fs_drbd then start mariadb
pcs constraint order start mariadb then start xCAT
pcs constraint order start mariadb then start keystone
pcs constraint order start keystone then start glance
pcs constraint order start keystone then start nova-controller

#--------------------------------------------------------------------------
# Create keystone endpoints for glance etc
#--------------------------------------------------------------------------
keystone_endpoint="http://controller.cluster:35357/v2.0"
for i in {1..60}; do
    if curl -s ${keystone_endpoint}; then 
        /tmp/trinity/keystone/keystone-setup.sh
        /tmp/trinity/keystone/glance-setup.sh
        /tmp/trinity/keystone/nova-setup.sh
        echo "Applied keystone initialization scripts"
        break
    fi
    echo "Waiting for keystone to come up!"
    sleep 30
done
[[ ${i} == 60 ]] && echo "Probably a timeout waiting for keystone to come up"

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
