#! /usr/bin/bash
##description    : The third round of High Availability.
##                 This will setup:
##                 1. Pacemaker configuration for the OpenStack Controller services
##                 This needs to be called after cv_install_dockerize.
##                 TODO: add openstack and trinity_api to this setup (contents of cv_install_openstack_on_controller)
##author         : Hans Then
##email          : hans.then@clustervision

#--------------------------------------------------------------------------
# Setup galera password and initial databases
#--------------------------------------------------------------------------
systemctl start galera

mysql=( mysql --protocol=tcp -uroot )
for i in {30..0}; do
    if echo 'SELECT 1' | "${mysql[@]}" &> /dev/null; then
        break
    fi
    echo 'MySQL init process in progress...'
    sleep 1
done
if [ "$i" = 0 ]; then
    echo >&2 'MySQL init process failed.'
    exit 1
fi

"${mysql[@]}" <<-EOSQL
    SET @@SESSION.SQL_LOG_BIN=0;

    DELETE FROM mysql.user ;
    CREATE USER 'root'@'%' IDENTIFIED BY 'system' ;
    GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
    DROP DATABASE IF EXISTS test ;
    FLUSH PRIVILEGES ;

    CREATE DATABASE keystone;
    GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY 'system';
    GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%'         IDENTIFIED BY 'system';
    CREATE DATABASE glance;
    GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost'     IDENTIFIED BY 'system';
    GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%'             IDENTIFIED BY 'system';
    CREATE DATABASE nova;
    GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost'         IDENTIFIED BY 'system';
    GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%'                 IDENTIFIED BY 'system';
    CREATE DATABASE cinder;
    GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost'     IDENTIFIED BY 'system';
    GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%'             IDENTIFIED BY 'system';
    FLUSH PRIVILEGES ;
EOSQL

#--------------------------------------------------------------------------
# Setup pacemaker
#--------------------------------------------------------------------------
pcs cluster cib config
# Setup high availability for the docker containers
pcs -f config resource create docker systemd:docker op monitor interval="37s"
pcs -f config resource clone docker clone-node-max=1 notify=false

pcs -f config resource create galera systemd:galera op monitor interval="37s"
pcs -f config resource clone galera clone-node-max=1 notify=false

pcs -f config resource create rabbitmq systemd:rabbitmq op monitor interval="37s"
pcs -f config resource create keystone systemd:keystone op monitor interval="37s"
pcs -f config resource create glance systemd:glance op monitor interval="37s"
pcs -f config resource create nova-controller systemd:nova-controller op monitor interval="37s"

pcs -f config resource group add grp_OpenStack rabbitmq keystone glance nova-controller
pcs -f config constraint colocation add grp_OpenStack ip
pcs -f config constraint order start fs_drbd then start galera
# This is only required when we run xCAT from inside galera
#pcs -f config constraint order start galera then start xCAT
pcs -f config constraint order start galera then start keystone
pcs -f config constraint order start keystone then start glance
pcs -f config constraint order start keystone then start nova-controller

pcs cluster cib-push config

#--------------------------------------------------------------------------
# Create keystone endpoints for glance etc
#--------------------------------------------------------------------------
keystone_endpoint="http://controller.cluster:35357/v2.0"
for i in {60..0}; do
    if curl -s ${keystone_endpoint}; then 
        /tmp/trinity/keystone/keystone-setup.sh
        /tmp/trinity/keystone/glance-setup.sh
        /tmp/trinity/keystone/nova-setup.sh
        echo "Applied keystone initialization scripts"
        break
    fi
    echo "Waiting for keystone to come up!"
    sleep 60
done
[[ ${i} == 0 ]] && echo "Timeout waiting for keystone to come up"

read ETH0 ETH1 ETH2 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
BRIDGE="br100"
PRI_NIC=${ETH1}
source /etc/profile.d/xcat.sh
sed -e "s/<TENANT>/admin/g" \
    -e "s/<USER>/admin/g" \
    -e "s/<PASSWORD>/system/g" \
    -e "s/<OPENSTACK>/10.141.255.254/g" \
    /trinity/openstack/keystonerc > /root/keystonerc_admin
source /root/keystonerc_admin

sed -e "s/eno2/${ETH1}/g" \
    -i /etc/trinity/trinity_api.conf

#-- Create the Flat Network
NETWORK_LABEL="novanetwork"
nova network-create \
       --fixed-range-v4 192.168.32.0/24 \
       --fixed-cidr 192.168.32.0/24 \
       --bridge-interface ${PRI_NIC} \
       --bridge ${BRIDGE} \
       ${NETWORK_LABEL}

#-- Download the base login node image (CentOS cloud image) and upload it to glance
# We have a sitemaster, copy from master node.
mkdir -p /trinity/qcows/
CLOUD_IMAGE="/trinity/qcows/login.qcow2"
# FIXME: Find a better location. We cannot assume /tmp/trinity is still mounted here.
cp /tmp/trinity/qcows/login.qcow2 ${CLOUD_IMAGE}
CLOUD_IMAGE_FORMAT="qcow2"
CLOUD_CONTAINER_FORMAT="bare"
LOGIN_IMAGE="login"
LOGIN_SETUP="/trinity/login/mini-setup.sh"

glance image-create \
    --name "${LOGIN_IMAGE}" \
    --disk-format "${CLOUD_IMAGE_FORMAT}" \
    --container-format "${CLOUD_CONTAINER_FORMAT}" \
    --file "${CLOUD_IMAGE}"

systemctl daemon-reload

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
