#! /usr/bin/bash
##description    : High Availability setup for the non-dockerized openstack HA services
## 	           This needs to be called after cv_install_openstack_on_controller
##author         : Hans Then
##email          : hans.then@clustervision

pcs cluster cib config
pcs -f config resource create trinity-api systemd:trinity-api op monitor interval="37s"
pcs -f config constraint colocation add trinity-api ip
pcs -f config constraint order start xCAT then start trinity-api
pcs -f config constraint order start httpd then start trinity-api
pcs cluster cib-push config
echo "$0 finished @ $(date)" >> /var/log/postinstall.log
