#! /usr/bin/bash
##description    : Make slapd highly available
##author         : Hans Then
##email          : hans.then@clustervision

me=$(hostname | egrep -o '[[:digit:]]*' | head -n1)
let other=me==1?2:1;

cat << EOF > /etc/openldap/cv_syncrepl
moduleload syncprov
serverid ${me}

overlay syncprov
syncprov-checkpoint 100 10
syncprov-sessionlog 100

syncrepl rid=200
         provider=ldap://controller-${other}.cluster:389
         type=refreshAndPersist
         retry="60 +"
         searchbase="dc=local"
         scope=sub
         schemachecking=on
         bindmethod=simple
         binddn="cn=Manager,dc=local"
         credentials=system

mirrormode on

##################################################
# Database for the monitoring #
##################################################
database monitor

access to *
       by dn.exact="cn=Manager,dc=local" read
       by * none

EOF

