#! /usr/bin/bash
##description    : High Availability setup for the non-dockerized openstack HA services
## 	           This needs to be called after cv_install_openstack_on_controller
##author         : Hans Then
##email          : hans.then@clustervision


#setup fencing
for i in {1..2}; do
    pcs resource create ipmi-${i} ocf:heartbeat:IPaddr2 ip="192.168.8.${i}" \
        iflabel="ipmi" cidr_netmask="24" nic="$CONTROLLER_PUBLIC_NIC" op monitor interval="37s"
    pcs constraint location ipmi-${i} prefers controller-${i}.$CONTROLLER_DOMAIN
#    pcs stonith create fence-${i} fence_ipmilan pcmk_host_list="controller-${i}.cluster" \
#        ipaddr="192.168.8.${i}" action="reboot" login="root" \
#        passwd="system" delay=15 op monitor interval=60s
done
pcs property set stonith-enabled=false

source /root/keystonerc_admin
for server in $(nova host-list --zone nova | grep compute | awk -F\| '{print $2}' | cut -b2-); do
    nova aggregate-create $server $server
    nova aggregate-add-host $server $server
done

# These are just for diagnostics
nova aggregate-list
nova availability-zone-list

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
