#! /usr/bin/bash
##description    : High Availability setup for the non-dockerized openstack HA services
## 	           This needs to be called after cv_install_openstack_on_controller
##author         : Hans Then
##email          : hans.then@clustervision

pcs resource create nova-compute systemd:openstack-nova-compute op monitor interval="37s"
pcs resource create nova-network systemd:openstack-nova-network op monitor interval="37s"
pcs resource create nova-metadata-api systemd:openstack-nova-metadata-api op monitor interval="37s"
pcs resource group add grp_NovaCompute nova-compute nova-network nova-metadata-api
pcs resource clone grp_NovaCompute clone-max=3 clone-node-max=1 notify=false

pcs resource create trinity-api lsb:trinity_api op monitor interval="37s"
pcs constraint colocation add ip with trinity-api
pcs constraint order start xCAT then start trinity_api
pcs constraint order start httpd then start trinity_api


pcs resource create sentinel ocf:pacemaker:Dummy
pcs constraint colocation add ip with sentinel
pcs constraint order start grp_xCAT then start sentinel
pcs constraint order start grp_OpenStack then start sentinel
pcs constraint order start trinity-api then start sentinel
pcs constraint order start grp_NovaCompute-clone then start sentinel

source /root/keystonerc_admin
for server in $(nova host-list --zone nova | grep compute | awk -F\| '{print $2}' | cut -b2-); do
    nova aggregate-create $server $server
    nova aggregate-add-host $server $server
done

# These are just for diagnostics
nova aggregate-list
nova availability-zone-list

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
