#! /usr/bin/bash
##description    : The second round of High Availability.
##                 This will setup:
##                 1. DRBD symlinks for the xCAT services (and docker-registry)
##                 2. Pacemaker configuration for the xCAT services
##author         : Hans Then
##email          : hans.then@clustervision

rm /etc/httpd/logs ; ln -s /var/log/httpd /etc/httpd/logs
rm /etc/httpd/modules ; ln -s /usr/lib64/httpd/modules /etc/httpd/modules
rm /etc/httpd/run ; ln -s /var/run/httpd /etc/httpd/run

cat <<EOF > /drbd/xcat.conf

restartSyslog(1)
cleanthisconfig(1)

#  One mountpoint must be listed.  This is the location where the DRBD
#  drive is mounted.
mountpoint('/drbd')
# ==== xCAT ====
link('/install')
link('/etc/xcat')
link('/opt/xcat')
link('/root/.xcat')
# Hosts is a bit odd - may just want to rsync out...
#link('/etc/hosts')
#
# ==== Conserver ====
link('/etc/conserver.cf')
#
# ==== DNS ====
# Named is active/active.
#link('/etc/named')
#link('/etc/named.conf')
#link('/etc/named.iscdlv.key')
#link('/etc/named.rfc1912.zones')
#link('/etc/named.root.key')
#link('/etc/rndc.conf')
#link('/etc/rndc.key')
#link('/etc/sysconfig/named')
#link('/var/named')

# ==== YUM ====
link('/etc/yum.repos.d')
#
# ==== DHCP ====
link('/etc/dhcp')
link('/var/lib/dhcpd')
link('/etc/sysconfig/dhcpd')
#link('/etc/sysconfig/dhcpd6')
#
# ==== Apache ====
link('/etc/httpd')
link('/var/www')
#
# ==== tftp ====
link('/tftpboot')
#
# ==== openldap ====
link('/etc/openldap')
link('/var/lib/ldap')
#
# ==== docker registry ====
link('/var/lib/docker-registry')

# ==== NFS ====
link('/etc/exports')
link('/var/lib/nfs')
link('/etc/sysconfig/nfs')
#
# === Trinity NFS shares ====
link('/trinity/')
link('/cluster/')
link('/home')
#
EOF

systemctl stop xcatd
systemctl stop docker-registry
systemctl stop nfs-server


drbdlinks -c /drbd/xcat.conf initialize_shared_storage
drbdlinks -c /drbd/xcat.conf start
systemctl start xcatd
systemctl start docker
systemctl start docker-registry
systemctl start nfs-server

#-------------------------------------------------------------------
# Now setup the common resources
#-------------------------------------------------------------------
dev=$(ip a | grep 10.148.255.253 | awk '{print $5}')

pcs resource create symlinks_xCAT ocf:tummy:drbdlinks configfile="/drbd/xcat.conf" op monitor interval="31s"

pcs resource create httpd systemd:httpd op monitor interval="37s"
pcs resource create dhcpd systemd:dhcpd op monitor interval="37s"
pcs resource create named systemd:named op monitor interval="37s"
pcs resource create nfs nfsserver nfs_no_notify=true op start timeout=240s
pcs resource create docker-registry systemd:docker-registry op monitor interval="37s"
pcs resource create slapd systemd:slapd op monitor interval="37s"
pcs resource create xCAT lsb:xcatd op monitor interval="42s"

pcs resource clone named clone-max=2 clone-node-max=1 notify=false

pcs resource group add grp_xCAT httpd dhcpd nfs docker-registry slapd xCAT
pcs constraint colocation add fs_drbd symlinks_xCAT
pcs constraint colocation add fs_drbd grp_xCAT

pcs constraint order start fs_drbd then start symlinks_xCAT
pcs constraint order start symlinks_xCAT then start grp_xCAT

echo pcs resource cleanup | at now +5 minutes

systemctl enable pacemaker
systemctl enable corosync

#Make xCAT available via the floating IP.
if grep -v XCATHOST /etc/profile.d/xcat.sh; then
    echo "export XCATHOST=controller.cluster:3001" >> /etc/profile.d/xcat.sh
fi

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
