#! /usr/bin/bash
##title          : cv_install_cinder
##description    : Configures cinder on the storage node.
##author         : Abhishek Mukherjee
##email          : abhishek.mukherjee@clustervision.com

# Main function
main(){
  # Parameters and constants
  NODE_IP=$(hostname -I| awk '{print $1}')
 # Set SeLinux to permissive mode
  setenforce 0

# Stop NetworkManager  
  systemctl stop NetworkManager
  systemctl disable NetworkManager
  killall dhclient
  systemctl start network

 
  echo "---- Configuring LVM ---"
  #AM: Packages installed by the pkglist
  #package_list=(
  #lvm2
  #)
  #install_packages package_list
  systemctl enable lvm2-lvmetad.service
  systemctl start lvm2-lvmetad.service
  
  # TODO: Do we also need to modify lvm.conf?
  # TODO: Add a partition table if necessary
  if vgdisplay | grep cinder-volumes ; then
    echo "Cinder-volumes exist!"
  else
    # This part is very similar to cv_configure_storage 
    # Should eventually be replaced with a call to that script
    # Remove existing volume groups
    umount -a -t ext4
    for VG in $(vgs --noheadings | grep -v "No Volumes" | awk -F' ' '{print $1}'); do 
      vgchange -a n ${VG}
      vgremove -f ${VG}
    done

    #DISK=$(lsblk --noheadings --list --output KNAME,TYPE | awk '{if ($2 == "disk") print $1}' | sort | head -1)
    #AM: Use all disks
    DISKS=$(lsblk --noheadings --list --output KNAME,TYPE | awk '{if ($2 == "disk") print $1}')
    for DISK in ${DISKS}; do 
      dd if=/dev/zero of=/dev/${DISK} bs=512 count=1
      blockdev --rereadpt /dev/${DISK}   
      # Create the LVM physical volume:
      pvcreate /dev/${DISK}
    done 
    # Create the LVM volume group cinder-volumes:
    vgcreate -f cinder-volumes $(for DISK in ${DISKS}; do echo -n /dev/${DISK}; echo -n " " ; done)
    # vgcreate cinder-volumes /dev/${DISK}
  fi

  
  echo "--- Configuring OpenStack Cinder ---- "
  #AM: Packages installed by the pkglist
  #package_list=(
  #epel-release 
  #targetcli
  #python-oslo-db
  #MySQL-python
  #openstack-utils
  #openstack-cinder
  #)
  # install_packages ${package_list}
  
  echo "--- Editing /etc/cinder/cinder.conf"
  # Set up access to the backend database
  openstack-config --set /etc/cinder/cinder.conf database connection mysql://cinder:${OPENSTACK_CINDER_PW}@${CONTROLLER_FIP}/cinder
  
  # Set up the message broker (rabbit_mq)
 # # -- NOTE: The rpc_password needs to be identical to that in the openstack controller
  # openstack-config --set /etc/cinder/cinder.conf DEFAULT rpc_backend rabbit
  openstack-config --set /etc/cinder/cinder.conf DEFAULT rpc_backend cinder.openstack.common.rpc.impl_kombu
  openstack-config --set /etc/cinder/cinder.conf DEFAULT rabbit_host $CONTROLLER_FIP
  openstack-config --set /etc/cinder/cinder.conf DEFAULT rabbit_password $OPENSTACK_RMQ_PW
  
  # set up the authentication service
  # -- NOTE: The admin_password needs to be identical to that in the openstack controller
  openstack-config --set /etc/cinder/cinder.conf DEFAULT auth_strategy keystone
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_uri http://$CONTROLLER_FIP:5000/v2.0
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken identity_uri http://$CONTROLLER_FIP:35357
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_tenant_name services
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_user cinder
  openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_password $OPENSTACK_CINDER_PW
  openstack-config --del /etc/cinder/cinder.conf keystone_authtoken auth_host
  openstack-config --del /etc/cinder/cinder.conf keystone_authtoken auth_port
  openstack-config --del /etc/cinder/cinder.conf keystone_authtoken auth_protocol
  
  # configure my_ip
  openstack-config --set /etc/cinder/cinder.conf DEFAULT my_ip ${NODE_IP}
  
  # configure cinder to use lioadm iSCSI service
  openstack-config --set /etc/cinder/cinder.conf DEFAULT iscsi_helper lioadm
  
  # configure the location of the Image service
  openstack-config --set /etc/cinder/cinder.conf glance host $CONTROLLER_FIP
  
  # enable verbose logging
  openstack-config --set /etc/cinder/cinder.conf DEFAULT verbose True
  echo "-----------------------------------"  
  
  systemctl enable openstack-cinder-volume.service target.service
  systemctl start openstack-cinder-volume.service target.service
}

# Main script
#AM: All log info fwd to /var/log/xcat/xcat.log
# start_logging ${LOGFILE}
#print_header "$(basename $0)"
main "$@"
#print_tail "$(basename $0)"
