#! /usr/bin/env bash
##title          : cv_install_first_cluster
##description    : Installs an first virtual cluster. 
##                 and then start the API server # service trinity_api start
##author         :  Abhishek Mukherjee
##email          :  abhishek.mukherjee@clustervision.com


source /root/keystonerc_admin
#-----------------------------------------------------------------------------------
# Create the default cluster
#-----------------------------------------------------------------------------------
FIRST_TENANT="a"
FIRST_USER="a"
FIRST_PASS="system"
FIRST_CLUSTER="vc-a"
FIRST_POOL="login_a"
FIRST_FLOATING="172.16.255.254"
LOGIN_SETUP="/trinity/login/mini-setup.sh"
LOGIN_DATA="/root/.setup-login-a"
LOGIN_NODE="login-a"
LOGIN_IMAGE="login"
SKEL=".skel"

keystone tenant-create --name ${FIRST_TENANT}
keystone user-create --name ${FIRST_USER} --tenant ${FIRST_TENANT} --pass ${FIRST_PASS}
nova floating-ip-bulk-create --pool ${FIRST_POOL} ${FIRST_FLOATING}
mkdir -p /cluster/${FIRST_CLUSTER}
cp -Tr /cluster/${SKEL}/ /cluster/${FIRST_CLUSTER}/
mkdir -p /nfshome/${FIRST_CLUSTER}

mkdir -p /cluster/${FIRST_CLUSTER}/etc/munge
[ -e  /cluster/${FIRST_CLUSTER}/etc/munge/munge.key ] && rm /cluster/${FIRST_CLUSTER}/etc/munge/munge.key
dd if=/dev/urandom bs=1 count=1024 > /cluster/${FIRST_CLUSTER}/etc/munge/munge.key
# FIXME munge userid is hardcoded to 1002 now.
chown -R 1002:1002 /cluster/${FIRST_CLUSTER}/etc/munge
chmod u=rwx,go= /cluster/${FIRST_CLUSTER}/etc/munge
chmod u=r,go=   /cluster/${FIRST_CLUSTER}/etc/munge/munge.key

#nodes=$(curl -k 'https://controller/xcatws/groups/vc-a/attrs/members?userName=trinity&password=trinity&pretty=1' | awk -F: '{if (NR==3) {print $2}}' | sed 's/"//g')
#sed -e "s/<NODES>/${nodes}/g" -i /cluster/${FIRST_CLUSTER}/etc/slurm/slurm-nodes.conf
touch /cluster/${FIRST_CLUSTER}/etc/slurm/slurm-nodes.conf
chmod u=rwx,go=rx /cluster/${FIRST_CLUSTER}/etc/slurm
chmod u=rw,go=rx  /cluster/${FIRST_CLUSTER}/etc/slurm/slurm.conf
chmod u=rw,go=r   /cluster/${FIRST_CLUSTER}/etc/slurm/slurm-nodes.conf
chmod ug=rw,o=r   /cluster/${FIRST_CLUSTER}/etc/slurm/slurm-user.conf

cp ${LOGIN_SETUP} ${LOGIN_DATA}

sed -e "s/FLOATING_IP=127.0.0.1/FLOATING_IP=${FIRST_FLOATING}/g" \
    -e "s/vc-a/${FIRST_CLUSTER}/g" \
    -e "s/UTC/$(date +%Z)/g" \
    -i "${LOGIN_DATA}"

sed -e "s/<TENANT>/${FIRST_TENANT}/g" \
    -e "s/<USER>/${FIRST_USER}/g" \
    -e "s/<PASSWORD>/${FIRST_PASS}/g" \
    -e "s/<OPENSTACK>/$(hostname -I | awk '{print $1}')/g" \
    /trinity/openstack/keystonerc > /root/keystonerc_${FIRST_TENANT}

chmod go-rw /root/keystonerc_${FIRST_TENANT} 
# Copy to failover node (not pretty)
scp /root/keystonerc_${FIRST_TENANT} controller-2.cluster:/root/keystonerc_${FIRST_TENANT}
source /root/keystonerc_${FIRST_TENANT}

nova secgroup-add-rule default tcp 1 65535 0.0.0.0/0
nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0

nova floating-ip-create ${FIRST_POOL}
nova boot --flavor 2 --image ${LOGIN_IMAGE} --security-groups default --user-data ${LOGIN_DATA} ${LOGIN_NODE}
sleep 5
nova floating-ip-associate ${LOGIN_NODE} ${FIRST_FLOATING}

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
