#! /usr/bin/bash
##title          : cv_install_openstack
##description    : Installs an openstack node. It also installs the Trinity API server, 
##                 the client and the dashboard additions
##                 and then start the API server # service trinity_api start
##author         : Hans Then & Abhishek Mukherjee
##email          : hans.then@clustervision
##                 abhishek.mukherjee@clustervision.com


#--------------------------------------------------------------------------------------
# copy the required files from the controller to the root file system
#--------------------------------------------------------------------------------------
mkdir /trinity
mount controller:/trinity /trinity       
cp --dereference --recursive --verbose --preserve /trinity/openstack/rootimg/* /

systemctl stop NetworkManager
systemctl disable NetworkManager

yum -y install openstack-packstack

sed "s/=127.0.0.1/=$(hostname -I)/g" //xcatpost/packstack-answers.txt > /tmp/packstack-answers.txt
read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
sed -e "s/\<eno1\>/$ETH1/g" -e "s/\<eno2\>/$ETH2/g"  -e "s/\<eno3\>/$ETH3/g" -i /tmp/packstack-answers.txt

export HOME=/root
packstack --answer-file /tmp/packstack-answers.txt
#packstack --allinone
# HTH: not required to inject passwords and keys, metadataservice is supposed to handle that.
#sed -i "s/^#\?inject_password=.*/inject_password=true/g" /etc/nova/nova.conf
#sed -i "s/^#\?inject_key=.*/inject_key=true/g" /etc/nova/nova.conf
sed -i "s/^#\?service_metadata_proxy=.*/service_metadata_proxy=False/g" /etc/nova/nova.conf
sed -i "s/'can_set_password':.*/'can_set_password': False,/g" /etc/openstack-dashboard/local_settings
systemctl restart openstack-nova-compute
systemctl restart openstack-nova-api
source ~/keystonerc_admin
nova floating-ip-bulk-delete 10.3.4.0/22

# Workaround for bug #67
killall dhclient
systemctl start network

mkdir -p /home
mkdir -p /cluster
mkdir -p /trinity

sort -u /etc/fstab* | \
  awk '
    BEGIN {print "# Created by trinity";}; \
    {if ($0!~/^\#/ && $0 !~/^$/) {if ($0~/nfs/) {nfs=nfs RS $0} else {local=local RS $0}}}; \
    END {print "# local filesystems" local RS "# remote filesystems" nfs}
  ' > /tmp/fstab
rm -f /etc/fstab*
mv -f /tmp/fstab /etc/fstab
##cp-rootimg
# FIXME: use a rootimg mechanism for this.
##if ! grep controller:/cluster /etc/fstab > /dev/null; then
##cat << END >> /etc/fstab
##controller:/cluster /cluster nfs rsize=8192,wsize=8192,timeo=14,intr
##controller:/trinity /trinity nfs rsize=8192,wsize=8192,timeo=14,intr
##controller:/home /home nfs rsize=8192,wsize=8192,timeo=14,intr
##END
##fi
mount -a

#--------------------------------------------------
# Install the API server
#--------------------------------------------------
# Assumes that /cluster and  /home are already mounted

# The Trinity API server init script requires the Linux Standard Base
yum -y install redhat-lsb

# The Trinity API server needs python Bottle
yum -y install epel-release
yum -y install python-pip
pip install bottle
pip install cherrypy

# Trinity API setup
cd /opt/trinity/trinity_api
python setup.py install
cd -
sed "s/127.0.0.1/$(hostname -I| awk '{print $1}')/g" /etc/trinity/trinity_api.conf > /tmp/trinity_api.conf
mv -f /tmp/trinity_api.conf /etc/trinity/trinity_api.conf
mkdir -p /var/log/trinity
mkdir -p /var/run/trinity

# Start the API
service trinity_api start
chkconfig trinity_api on

#--------------------------------------------------
# Install the python client
#--------------------------------------------------
cd /opt/trinity/trinity_client
python setup.py install
cd -
sed "s/127.0.0.1/$(hostname -I| awk '{print $1}')/g" /etc/trinity/trinity_client.conf > /tmp/trinity_client.conf
mv -f /tmp/trinity_client.conf /etc/trinity/trinity_client.conf

#--------------------------------------------------
# Install the dashboard additions
#--------------------------------------------------
cd /opt/trinity/trinity_dashboard
sh setup.sh
cd -

# This is to fix a bug in the httpd configuration needed for Juno
echo 'Include "/etc/httpd/conf.modules.d/*.conf"' >> /etc/httpd/conf/httpd.conf

service httpd restart




