#!/usr/bin/env bash
##title          : cv_install_containers
##description    : Sets up a dockerized infrastructure.
##                 The following services are dockerized
##                   MariaDB (Database)
##                   RabbitMQ (Message Queue)
##                   Keystone (OpenStack Identity)
##                   Glance (OpenStack Image)
##                   Nova controller (OpenStack Compute: controller part)
##author         : Abhishek Mukherjee, Hans Then
##email          : abhishek.mukherjee@clustervision.com, hans.then@clustervision.com

#------------------------------------------------------------------------------
# Setup the dockerized components
#------------------------------------------------------------------------------
systemctl start docker
REGISTRY="controller:5050"
TOPDIR="/trinity"
profiles=(
  "galera"
  "rabbitmq"
  "keystone"
  "glance"
  "nova_controller"        
)
keystone_endpoint="http://controller.cluster:35357/v2.0"

for profile in "${profiles[@]}"; do
  if [ -z ${SITEMASTER} ]; then
      docker build --rm=true -t ${REGISTRY}/${profile} ${TOPDIR}/${profile}
  else
      docker pull ${SITEMASTER}:5050/${profile} 
      docker tag ${SITEMASTER}:5050/${profile} ${REGISTRY}/${profile}
  fi
      
  cp -LrT /tmp/${TOPDIR}/${profile}/host/rootimg /
done

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
