#! /usr/bin/env python
##title          : cv_install_moncon
##description    : Configures the monitoring server: adds hosts from the xCAT db and static (hardware groups).
##author         : Abhishek Mukherjee, Hans Then
##email          : abhishek.mukherjee@clustervision.com, hans.then@clustervision.com

import sys
import subprocess
import requests
import json

# For now hardcoding the files and IPs. 
default_xcat_host="10.141.255.254"
default_xcat_query={'userName':'trinity', 'password':'trinity', 'pretty':'1'}
default_monitoring='monitoring'
# HTH default_hosts_file="/opt/omd/sites/"+default_monitoring+"/etc/check_mk/conf.d/wato/hosts.mk"
# HTH default_aggr_file="/opt/omd/sites/"+default_monitoring+"/etc/check_mk/multisite.mk"

default_hosts_file="/cluster/omd/conf.d/hosts.mk"
default_aggr_file="/cluster/omd/multisite.d/multisite.mk"

class MonCon(object):
  def __init__(self,xcat_host,xcat_query,monitoring,hosts_file,aggr_file): 
    self.xcat_host=xcat_host
    self.xcat_query=xcat_query
    self.monitoring=monitoring
    self.hosts_file=hosts_file
    self.aggr_file=aggr_file

  def get_hosts_from_xcat(self):
    #node_list=requests.get("https://"+self.xcat_host+"/xcatws"+"/nodes", verify=False, params=self.xcat_query).json()
    compute=requests.get("https://"+self.xcat_host+"/xcatws"+"/groups/compute", verify=False, params=self.xcat_query).json()
    storage=requests.get("https://"+self.xcat_host+"/xcatws"+"/groups/storage", verify=False, params=self.xcat_query).json()
    node_list = compute['compute']['members'].split(',') + storage['storage']['members'].split(',')

    print node_list
    def chunks(l, n):
        """Yield successive n-sized chunks from l."""
        for i in xrange(0, len(l), n):
            yield l[i:i+n]

    hosts_dict={}
    for chunk in chunks(node_list, 50):
        node_string=",".join(chunk)
        print node_string
        node_info=requests.get("https://"+self.xcat_host+"/xcatws"+"/nodes/"+node_string, verify=False, params=self.xcat_query).json()
        for node,node_dict in node_info.iteritems():
            try:
                host_ip=node_dict['ip']
                # Try hostname first, if not use node name
                try:
                    hostnames=node_dict['hostnames'].strip().split(',')
                    host_name=hostnames[0]
                except:
                    host_name=node
                hosts_dict.update({host_name : host_ip})
            except:
                print 'No IP address for node: '+node  
    return hosts_dict  

  def add_hosts(self,hosts_dict):
    with open(self.hosts_file,'w') as fop:
      for host_name,host_ip in hosts_dict.iteritems():
        host='all_hosts += [ \"'+host_name+'|cmk-agent|prod|lan|tcp|wato|/\" + FOLDER_PATH + \"/\", ]'
        fop.write('\n'+host+'\n')
    print "ALL HOSTS: Added host "+host_name

  def get_groups_from_xcat(self):
    group_list=requests.get("https://"+self.xcat_host+"/xcatws"+"/groups", verify=False, params=self.xcat_query).json()
    group_string=",".join(group_list)
    group_info=requests.get("https://"+self.xcat_host+"/xcatws"+"/groups/"+group_string, verify=False, params=self.xcat_query).json()
    groups_dict={}
    for group,group_dict in group_info.iteritems():
      if group.startswith('vc') or group.startswith('hw'):
        continue
      members_string=group_dict['members'].strip()
      if members_string:
        members_list=members_string.split(",")
        groups_dict.update({group:members_list})
      else:
        groups_dict.update({group:[]})
    return groups_dict  

  # this should also work for static virtual clusters, but not for updating
  def add_hw_aggrs(self,groups_dict,hw='hw-'):
    rule="ping"
    desc="PING"
    func="worst"
    check="PING"
    with open(self.aggr_file,'a') as fop:
      aggr_rule='aggregation_rules[\"ping\"] = (\"PING\", [ "HOST" ], \"worst\", [( \"$HOST$\", \"PING\" ),])'
      fop.write("\n"+aggr_rule+"\n")
      for group,members in groups_dict.iteritems():
        if group.startswith(hw):
          len_hw=len(hw)
          aggr=group[len_hw:]
          #self.add_aggr(aggr,members)
          for host_name in aggr_members:
            aggregation='aggregations += [( \"'+aggr_name+'\", \"'+check+'\", [\"'+host_name+'\"]),]'
            fop.write("\n"+aggregation+"\n")
      
################################################################################################## 


def main(xcat_host,xcat_query,monitoring,hosts_file,aggr_file):
  
  mc=MonCon(xcat_host,xcat_query,monitoring,hosts_file,aggr_file)
  # Add hosts from the xCAT db
  hosts_dict=mc.get_hosts_from_xcat()
  mc.add_hosts(hosts_dict)
  cmd = 'docker exec -u monitoring omd bash -lc "check_mk -R"'
  subprocess.call(cmd,shell=True)  

  # For now only adding pingability 
  groups_dict=mc.get_groups_from_xcat()
  mc.add_hw_aggrs(groups_dict)


if __name__=='__main__':  
  main(default_xcat_host,default_xcat_query,default_monitoring,default_hosts_file,default_aggr_file)
### python echo "$0 finished @ $(date)" >> /var/log/postinstall.log  
