#! /usr/bin/bash
#title		: cv_install_agent
#description	: Installs the check_mk monitoring agent on worker nodes
#author		: Abhishek Mukherjee
#email		: abhishek.mukherjee@clustervision.com

yum install -y wget telnet net-tools

# Workaround for #364
yum -y reinstall xinetd
chkconfig xinetd on
service xinetd start
# This is a temporary measure 
# The rpm should either be in the local repo 
# or we should make sure that we download a consistent version of the rpm
wget https://mathias-kettner.de/download/check_mk-agent-1.2.4p5-1.noarch.rpm
wget https://mathias-kettner.de/download/check_mk-agent-logwatch-1.2.4p5-1.noarch.rpm
yum install -y check_mk-agent*.rpm
service xinetd restart
iptables -F
echo "$0 finished @ $(date)" >> /var/log/postinstall.log
