#! /usr/bin/bash
#title		: cv_install_rsa
#description	: Installs the monitoring service from OMD on the monitoring server
#author		: Abhishek Mukherjee
#email		: abhishek.mukherjee@clustervision.com

if [ -z ${SITEMASTER} ]; then
    docker build --rm=true -t controller:5050/omd /trinity/omd
else
    docker pull ${SITEMASTER}:5050/omd
    docker tag ${SITEMASTER}:5050/omd controller:5050/omd
fi

mkdir -p /cluster/omd/multisite.d
mkdir -p /cluster/omd/conf.d
chown 997:1000 /cluster/omd/*
chmod g+ws /cluster/omd/*

docker run -d -t --name=omd \
    -p 5003:5003 \
    --dns=10.141.255.254 \
    -v /cluster/omd/conf.d:/opt/omd/sites/monitoring/etc/check_mk/conf.d/trinity \
    -v /cluster/omd/multisite.d:/opt/omd/sites/monitoring/etc/check_mk/multisite.d/trinity \
    controller:5050/omd 

systemctl enable omd.service
systemctl start omd.service

echo "$0 finished @ $(date)" >> /var/log.postinstall.log

