#!/usr/bin/env bash
##title          : cv_install_compute_on_controller
##description    : Setup the openstack compute services baremetal on controller
##                   Nova compute and network (openstack-nova-compute and openstack-nova-network)
##author         : Abhishek Mukherjee, Hans Then
##email          : abhishek.mukherjee@clustervision.com, hans.then@clustervision.com

#------------------------------------------------------------------------------
# Install and configure openstack-nova-compute and openstack-nova-network 
#------------------------------------------------------------------------------
# Get config info
source /trinity/nova/config.sh

# Parameters and constants
NODE_IP=$(hostname -i)

# Set SeLinux to permissive mode
setenforce 0
systemctl stop openstack-nova-compute.service openstack-nova-network.service openstack-nova-metadata-api.service

#-- Configure the openstack-nova-compute component

echo "----Configuring openstack-nova-compute: editing /etc/nova/nova.conf----"
# Set up the message broker (rabbit_mq)
# -- NOTE: The rpc_password needs to be identical to that in the openstack controller
# -- NOTE: Please, ensure that the entries below are identical to that on the openstack controller
#openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend rabbit
openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend nova.openstack.common.rpc.impl_kombu
openstack-config --set /etc/nova/nova.conf DEFAULT rabbit_host  ${OPENSTACK_CONTROLLER}
openstack-config --set /etc/nova/nova.conf DEFAULT rabbit_password ${RPC_PASS}

# set up the authentication service
# -- NOTE: The admin_password needs to be identical to that in the openstack controller
openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_uri http://${OPENSTACK_CONTROLLER}:5000/v2.0
openstack-config --set /etc/nova/nova.conf keystone_authtoken identity_uri http://${OPENSTACK_CONTROLLER}:35357
openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_tenant_name services
openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_user nova
openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_password ${NOVA_PASS}
openstack-config --del /etc/nova/nova.conf keystone_authtoken auth_host
openstack-config --del /etc/nova/nova.conf keystone_authtoken auth_port
openstack-config --del /etc/nova/nova.conf keystone_authtoken auth_protocol

# configure my_ip
openstack-config --set /etc/nova/nova.conf DEFAULT my_ip ${NODE_IP}

# setup remote console access
openstack-config --set /etc/nova/nova.conf DEFAULT vnc_enabled True
openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_lister 0.0.0.0
openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address ${NODE_IP}
openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://${OPENSTACK_CONTROLLER}:6080/vnc_auto.html

# configure the location of the Image service
openstack-config --set /etc/nova/nova.conf glance host ${OPENSTACK_CONTROLLER}

# enable verbose logging
openstack-config --set /etc/nova/nova.conf DEFAULT verbose True

# Fixes #556, start login nodes after reboot
openstack-config --set /etc/nova/nova.conf DEFAULT resume_guests_state_on_host_boot true

echo "-----------------------------------"


#-- Configure the openstack-nova-network component

echo "----Configuring openstack-nova-network: editing /etc/nova/nova.conf----"
# Parameters and constants
read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
PUB_NIC=${ETH2}
PRI_NIC=${ETH3} 

openstack-config --set /etc/nova/nova.conf DEFAULT network_api_class  nova.network.api.API
openstack-config --set /etc/nova/nova.conf DEFAULT security_group_api  nova
openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver  nova.virt.libvirt.firewall.IptablesFirewallDriver
openstack-config --set /etc/nova/nova.conf DEFAULT network_manager  nova.network.manager.FlatDHCPManager
openstack-config --set /etc/nova/nova.conf DEFAULT network_size  254
openstack-config --set /etc/nova/nova.conf DEFAULT allow_same_net_traffic  False
openstack-config --set /etc/nova/nova.conf DEFAULT multi_host  True
openstack-config --set /etc/nova/nova.conf DEFAULT send_arp_for_ha  True
openstack-config --set /etc/nova/nova.conf DEFAULT share_dhcp_address  True
openstack-config --set /etc/nova/nova.conf DEFAULT force_dhcp_release  True
openstack-config --set /etc/nova/nova.conf DEFAULT flat_network_bridge  br100
openstack-config --set /etc/nova/nova.conf DEFAULT flat_interface  ${PRI_NIC}
openstack-config --set /etc/nova/nova.conf DEFAULT vlan_interface  ${PRI_NIC}
openstack-config --set /etc/nova/nova.conf DEFAULT public_interface  ${PUB_NIC}
echo "-----------------------------------"

# Start virtualization and nova-compute
systemctl restart libvirtd.service openstack-nova-compute.service
systemctl enable  libvirtd.service 
systemctl start openstack-nova-network.service
systemctl start openstack-nova-metadata-api.service

systemctl daemon-reload

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
