#! /usr/bin/bash
#title		: cv_install_rsa
#description	: Installs the monitoring service from OMD on the monitoring server
#author		: Abhishek Mukherjee
#email		: abhishek.mukherjee@clustervision.com

if [ -z ${SITEMASTER} ]; then
    docker build --rm=true -t controller:5050/omd /trinity/omd
else
    docker pull ${SITEMASTER}:5050/omd
    docker tag ${SITEMASTER}:5050/omd controller:5050/omd
fi

mkdir -p /cluster/omd/multisite.d
mkdir -p /cluster/omd/conf.d
chown 997:1000 /cluster/omd/*
chmod g+ws /cluster/omd/*

cp -LrT /tmp/trinity/omd/host/rootimg /
systemctl start omd.service

echo "$0 finished @ $(date)" >> /var/log/postinstall.log

