#! /usr/bin/bash
##title          : cv_install_controller
##description    : Installs an xCAT controller node. Additionally it also configures
##                 the xCAT web service 
##author         : Hans Then & Abhishek Mukherjee
##email          : hans.then@clustervision
##                 abhishek.mukherjee@clustervision.com


# see http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
#exec > >(tee /var/log/postinstall.log)
#exec 2>&1

#--------------------------------------------------------------------------------------
# install xcat
#--------------------------------------------------------------------------------------
# HTH: added to make sure the network is up
sleep 10

mkdir /tmp/trinity
mount master:/trinity /tmp/trinity       
mkdir /trinity

#--------------------------------------------------------------------------------------
# copy required files from the master node to the controller node
#--------------------------------------------------------------------------------------
cp --dereference --recursive --verbose --preserve /tmp/trinity/controller/rootimg/* /
cp /tmp/trinity/version /trinity/version


# copy all required module files etc to the right locations
# note to self: only /trinity/env needs be mounted inside the container
# FIXME: this takes an awful amount of time
cp --dereference --recursive --verbose --preserve /tmp/trinity/clustervision /trinity &

#--------------------------------------------------------------------------------------
# HTH: disable this
# enable all repositories inside the controller
# but disable the local repo from master
#--------------------------------------------------------------------------------------
#cd /etc/yum.repos.d
#for file in * ; do sed -i 's/enabled=0/enabled=1/g' $file; done
#sed -i 's/enabled=1/enabled=0/g' local-repository.repo
#cd -


#--------------------------------------------------------------------------------------
# create runimages
#--------------------------------------------------------------------------------------
for file in $(ls /install/runimages); do
    if [ -d /install/runimages/${file} ]; then 
        tar czf /install/runimages/${file}.tgz -C /install/runimages/${file}/ .
    fi
done


#--------------------------------------------------------------------------------------
# copy default database configuration
# copy the cd first, as otherwise copycds will overwrite the linuximage table
# and patch the installation
#--------------------------------------------------------------------------------------
source /etc/profile.d/xcat.sh
mkdir -p /tmp/xcattables
read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
for table in $(ls /tmp/trinity/controller/xcat/tables); do
    sed -e "s/\<eno1\>/$ETH1/g" -e "s/\<eno2\>/$ETH2/g"  -e "s/\<eno3\>/$ETH3/g" /tmp/trinity/controller/xcat/tables/$table > /tmp/xcattables/$table;
done

restorexCATdb -p /tmp/xcattables  

# Fix for #149
ip addr a 10.141.255.254/16 dev $ETH2
cd /opt/xcat/share/xcat/netboot/centos
ln -s ../rh/dracut_033 .
ln -s ../rh/dracut .

cd /
cat /tmp/trinity/controller/xcat/patches/*.patch | patch -p0
systemctl restart xcatd
systemctl enable ntpd
systemctl start ntpd
makedhcp -n
makehosts -n
makedns -n

#--------------------------------------------------------------------------------------
# correct any network settings
#--------------------------------------------------------------------------------------

# setup NAT, so nodes can access the internet (see manual step 1.f)
chkconfig iptables on
service iptables start
modprobe iptable_nat
iptables -A FORWARD -i $ETH2 -j ACCEPT
iptables -t nat -A POSTROUTING -o $ETH1 -j MASQUERADE
iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited
service iptables save

#--------------------------------------------------------------------------------------
# setup routing for the virtual clusters
#--------------------------------------------------------------------------------------
ip route add 172.16.0.0/12 dev $ETH2
mv /etc/sysconfig/network-scripts/route-eno2 /etc/sysconfig/network-scripts/route-${ETH2}

##AM: This is not required, assuming that everything is already written into route-eno2
#mv -f /etc/sysconfig/network-scripts/route-eno2-trinity /etc/sysconfig/network-scripts/route-${ETH2}-trinity
#sort -u /etc/sysconfig/network-scripts/route-${ETH2}* | \
#  awk ' \
#    BEGIN {print "# Created by trinity";}; \
#    {if ($0!~/^\#/ && $0 !~/^$/) {route=route RS $0}}; \
#    END {print route}
#  ' > /tmp/route-${ETH2}
#rm -f /etc/sysconfig/network-scripts/route-${ETH2}*
#mv -f /tmp/route-${ETH2} /etc/sysconfig/network-scripts/route-${ETH2}

##cp-rootimg
##cat << END > /etc/sysconfig/network-scripts/route-$ETH2 
##ADDRESS0=172.16.0.0
##NETMASK0=255.240.0.0
##END



#--------------------------------------------------------------------------------------
# Start opensm on the controller
#--------------------------------------------------------------------------------------
yum -y groupinstall "Infiniband Support"
yum -y install opensm
yum -y install infiniband-diags

systemctl enable opensm
systemctl start opensm

#--------------------------------------------------------------------------------------
# now setup NFS exports
#--------------------------------------------------------------------------------------
systemctl enable nfs-server
systemctl start nfs-server

##AM: Using the exports.d mechanism 
#sort -u /etc/exports* | \
#  awk ' \
#    BEGIN {print "# Created by trinity";}; \
#    {if ($0!~/^\#/ && $0 !~/^$/) {exports=exports RS $0}}}; \
#    END {print exports}
#  ' > /tmp/exports
#rm /etc/exports*
#mv /tmp/exports /etc/exports
##cp-rootimg
##cat << END > /etc/exports 
##/tftpboot *(rw,no_root_squash,sync,no_subtree_check)
##/install *(rw,no_root_squash,sync,no_subtree_check)
##/trinity *(rw,sync,no_root_squash,no_all_squash)
##/cluster *(rw,sync,no_root_squash,no_all_squash)
##/home *(rw,sync,no_root_squash,no_all_squash)
##END

exportfs -a

#--------------------------------------------------------------------------------------
# Selective updates
# Create installation tree
#--------------------------------------------------------------------------------------
iso=$(ls -c /tmp/trinity/iso/*.iso | head -1)
echo "Creating installation tree from $iso"
copycds -o -n centos7.0 $iso
mkdir -p /install/post/otherpkgs/centos7.0/x86_64
reposync -n -r xcat-otherpkgs0 -p /install/post/otherpkgs/centos7.0/x86_64/
createrepo /install/post/otherpkgs/centos7.0/x86_64/

genimage centos7.0-x86_64-netboot-trinity
packimage centos7.0-x86_64-netboot-trinity

#---------------------------------------------------------------------------------------
# Workaround: create a default munge key for vc-a cluster
#---------------------------------------------------------------------------------------
mkdir -p /cluster/vc-a/etc/munge/
dd if=/dev/urandom bs=1 count=1024 >/cluster/vc-a/etc/munge/munge.key
chmod 400 /cluster/vc-a/etc/munge/munge.key
chown 1002:1002 /cluster/vc-a/etc/munge/munge.key

#--------------------------------------------------------------------------------------
# install docker and docker-registry
# and create the trinity image for the compute nodes
#--------------------------------------------------------------------------------------
yum -y install docker docker-registry
sed -i 's/REGISTRY_PORT=.*/REGISTRY_PORT=5050/' /etc/sysconfig/docker-registry
sed -i 's/OPTIONS=\(.*\)/OPTIONS=--insecure-registry controller:5050 --bip=10.146.255.254\/16 --fixed-cidr=10.146.255.255\/16 \1/' /etc/sysconfig/docker
echo "10.141.255.254 controller" >>  /etc/hosts
systemctl enable docker docker-registry
systemctl start docker docker-registry
docker build -t controller:5050/trinity /trinity/container
docker push controller:5050/trinity

#--------------------------------------------------------------------------------------
# cleanup
#--------------------------------------------------------------------------------------

#umount /tmp/trinity
#rmdir /tmp/trinity

#--------------------------------------------
# Install the xCAT web service
#--------------------------------------------
# The xCAT web service requires the following
yum -y install mod_ssl
service httpd restart
yum -y install perl-JSON

# Set up the xCAT web service
useradd trinity
echo "trinity" | passwd trinity --stdin
source /etc/profile.d/xcat.sh
export HOME=/root
tabch key=xcat,username=trinity passwd.password=trinity
mkdef -t policy 6 name=trinity rule=allow
sed  -e "/<Directory \/>/,/<\/Directory>/ s/Require/#Require/" -i /etc/httpd/conf/httpd.conf
service httpd restart

exit 0

