#!/bin/bash

#----------------------------------------------------------------------------
# Install OpenLDAP on the controller node
#----------------------------------------------------------------------------
systemctl start docker

if [ -z ${SITEMASTER} ]; then
    docker build --rm=true -t controller:5050/opendlap /trinity/openldap
else
    docker pull ${SITEMASTER}:5050/openldap
    docker tag ${SITEMASTER}:5050/openldap controller:5050/openldap
fi

cp -LrT /tmp/trinity/openldap/host/rootimg /
cp /tmp/trinity/openldap/rootimg/usr/sbin/obol /usr/local/sbin/

systemctl enable slapd 
systemctl start slapd

#----------------------------------------------------------------------------
# Setup the local database
#----------------------------------------------------------------------------
ldapadd -D cn=Manager,dc=local -w system << EOF
dn: dc=local
dc: local
objectClass: domain

dn: ou=People,dc=local
ou: People
objectClass: top
objectClass: organizationalUnit

dn: ou=Group,dc=local
ou: Group
objectClass: top
objectClass: organizationalUnit

dn: cn=uid,dc=local
cn: uid
objectClass: uidNext
uidNumber: 1050

dn: cn=gid,dc=local
cn: gid
objectClass: uidNext
uidNumber: 150
EOF

obol -w system group add power-users

#----------------------------------------------------------------------------
# Setup PAM
#----------------------------------------------------------------------------
yum -y -q install sssd authconfig

chmod 600 /etc/sssd/sssd.conf
systemctl enable sssd
systemctl start sssd

authconfig --enablemkhomedir --enablesssd --enablesssdauth --update

echo "$0 finished @ $(date)" >> /var/log/postinstall.log
