#!/bin/bash

yum -y install python-retrying python-ldap
cp /trinity/login/rootimg/usr/sbin/obol /usr/sbin

export OS_SERVICE_TOKEN=$(openstack-config --get /etc/keystone/keystone.conf DEFAULT admin_token)
export OS_SERVICE_ENDPOINT=http://localhost:35357/v2.0

openstack-config --set /etc/keystone/keystone.conf ldap url ldap://controller
openstack-config --set /etc/keystone/keystone.conf ldap user cn=Manager,dc=cluster
openstack-config --set /etc/keystone/keystone.conf ldap query_scope sub
openstack-config --set /etc/keystone/keystone.conf ldap password system
openstack-config --set /etc/keystone/keystone.conf ldap suffix dc=cluster
openstack-config --set /etc/keystone/keystone.conf ldap use_dumb_member  False
openstack-config --set /etc/keystone/keystone.conf ldap allow_subtree_delete  False

openstack-config --set /etc/keystone/keystone.conf ldap user_tree_dn dc=cluster
openstack-config --set /etc/keystone/keystone.conf ldap user_objectclass posixAccount

openstack-config --set /etc/keystone/keystone.conf ldap group_tree_dn dc=cluster
openstack-config --set /etc/keystone/keystone.conf ldap group_objectclass posixGroup

openstack-config --set /etc/keystone/keystone.conf ldap user_enabled_attribute disabled
openstack-config --set /etc/keystone/keystone.conf ldap user_enabled_default False
openstack-config --set /etc/keystone/keystone.conf ldap user_enabled_invert True
openstack-config --set /etc/keystone/keystone.conf identity driver keystone.identity.backends.ldap.Identity
openstack-config --set /etc/keystone/keystone.conf assignment driver keystone.assignment.backends.sql.Assignment

systemctl restart openstack-keystone || (echo Error restarting keystone; exit 0)

files=$(grep -R "^admin_user=" /etc 2> /dev/null | awk -F: '{print $1'})
for file in $files; do
    echo $file
    if [ "$file" = "/etc/glance/glance-registry.conf" ]; then continue; fi 
    user=$(openstack-config --get $file "keystone_authtoken" admin_user)
    tenant=$(openstack-config --get $file keystone_authtoken admin_tenant_name)
    password=$(openstack-config --get $file keystone_authtoken admin_password)
    if [ -n "$user" ]; then
        # obol user add
        obol -H ldap://controller -w system user add "$user" --password "$password" --cn "$user" --sn "$user" --givenName "$user" 
        # assign the service admin role in the tenant
        keystone user-role-add --user=$user --tenant=services --role=admin
    fi
done

password=$(grep "export OS_PASSWORD=" /root/keystonerc_admin | cut -d= -f2)
obol -H ldap://controller -w system user add "admin" --password "$password" --cn "admin" --sn "admin" --givenName "admin"
keystone user-role-add --user=admin --tenant=admin --role=admin
keystone user-role-add --user=admin --tenant=admin --role=_member_

obol -H ldap://controller -w system user add "a" --password "system" --cn "a" --sn "a" --givenName "a"
keystone user-role-add --user=a --tenant=a --role=admin
keystone user-role-add --user=a --tenant=a --role=_member_

