#!/usr/bin/python
import os
for i in range(1, int(os.environ['NETWORKS_LINES'])):
    network = os.environ['NETWORKS_LINE%d' % i]
    hash = {}
    for item in network.split('||'): 
        key, value = item.split('=')
        hash[key] = value
    print hash
