#! /usr/bin/bash
##title          : cv_setup_xcatdb
##description    : Changes the xcat database to a (dockerized) mariadb
##author         : Hans Then 
##email          : hans.then@clustervision

yum -y install perl-DBD-MySQL

source /etc/profile.d/xcat.sh
docker run -p 3306:3306 --name=db -it -d -e MYSQL_ROOT_PASSWORD=system mariadb
while ! docker logs db | grep "ready for connections"; do
    sleep 1; 
    echo "waiting until db is started"; 
done

dumpxCATdb -p /tmp/xcattables

docker exec db /usr/bin/mysql -psystem -e "create database xcatdb;"
docker exec db /usr/bin/mysql -psystem -e "CREATE USER xcatadmin IDENTIFIED BY 'system';"
docker exec db /usr/bin/mysql -psystem -e "GRANT ALL on xcatdb.* TO xcatadmin@'%' IDENTIFIED BY 'system';"

echo "mysql:dbname=xcatdb;host=10.141.255.254|xcatadmin|system" > /etc/xcat/cfgloc
XCATBYPASS=y restorexCATdb -p /tmp/xcattables
systemctl restart xcatd

echo "The xcat db is now running from a dockerized mariadb"
echo $0 finished >> /var/log/postinstall.log
