#! /usr/bin/bash
##title          : cv_setup_xcatdb
##description    : Changes the xcat database to a (dockerized) mariadb
##author         : Hans Then 
##email          : hans.then@clustervision

source /etc/profile.d/xcat.sh
yum -y install mariadb-devel mariadb-libs mariadb-server mariadb-bench mariadb perl-DBD-MySQL mysql-connector-odbc unixODBC
export TERM=dumb
export XCATMYSQLADMIN_PW=system
export XCATMYSQLROOT_PW=system
mysqlsetup -i -V

mysqldump --databases xcatdb > /root/xcatdb.sql
systemctl stop mariadb

docker run -p 3306:3306 --name=db -i -d -e MYSQL_ROOT_PASSWORD=system mariadb
echo "create database xcatdb" | docker exec -i db /usr/bin/mysql -psystem
echo "GRANT ALL on xcatdb.* TO xcatadmin@'%' IDENTIFIED BY 'system';" | docker exec -i db mysql -psystem
docker exec -i db mysql -psystem xcatdb < /root/xcatdb.sql;
