#!/bin/bash
#
#       /etc/rc.d/init.d/trinity
#
#       Daemon for trinity compute nodes
#       
# chkconfig:   2345 95 95
# description: Daemon for trinity

### BEGIN INIT INFO
# Provides:       trinity
# Required-Start: $network docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop trinity
# Description: Daemon for trinity
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    /usr/sbin/trinity-start &
}

stop() {
    echo -n "Stopping trinity "
    docker stop trinity
}

restart() {
    stop
    start
}

reload() {
    restart
}

force-reload() {
    docker stop trinity
    docker rm trinity
    start
}

rh_status() {
    state=$(docker inspect --format='{{.State.Running}}' trinity 2>/dev/null)
    test -n "$state" -a "$state" = true
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        force-reload
        ;;
    force-reload)
        force-reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac

exit $?
