#!/bin/bash

# see http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
#exec > >(tee /var/log/postinstall.log)
#exec 2>&1

#--------------------------------------------------------------------------------------
# install xcat
#--------------------------------------------------------------------------------------
# HTH: added to make sure the network is up
sleep 10

ls /etc/yum.repos.d 
yum repolist

yum -y install xCAT 

mkdir /tmp/trinity
mount master:/trinity /tmp/trinity       
mkdir /trinity

# copy all required module files etc to the right locations
# note to self: only /trinity/env needs be mounted inside the container
# FIXME: this takes an awful amount of time
cp -r /tmp/trinity/clustervision /trinity &

#--------------------------------------------------------------------------------------
# enable all repositories inside the controller
# but disable the local repo from master
#--------------------------------------------------------------------------------------
cd /etc/yum.repos.d
for file in * ; do sed -i 's/enabled=0/enabled=1/g' $file; done
sed -i 's/enabled=1/enabled=0/g' local-repository.repo
cd -

#--------------------------------------------------------------------------------------
# copy required files from the master node to the controller node
#--------------------------------------------------------------------------------------
cp -r /tmp/trinity/controller/rootimg/* / 
cp /tmp/trinity/version /trinity/version

#--------------------------------------------------------------------------------------
# create runimages
#--------------------------------------------------------------------------------------
for file in $(ls /install/runimages); do
    if [ -d /install/runimages/${file} ]; then 
        tar czf /install/runimages/${file}.tgz -C /install/runimages/${file}/ .
    fi
done


#--------------------------------------------------------------------------------------
# copy default database configuration
# copy the cd first, as otherwise copycds will overwrite the linuximage table
# and patch the installation
#--------------------------------------------------------------------------------------
source /etc/profile.d/xcat.sh
mkdir -p /tmp/xcattables
read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
for table in $(ls /tmp/trinity/controller/xcat/tables); do
    sed -e "s/\<eno1\>/$ETH1/g" -e "s/\<eno2\>/$ETH2/g"  -e "s/\<eno3\>/$ETH3/g" /tmp/trinity/controller/xcat/tables/$table > /tmp/xcattables/$table;
done

restorexCATdb -p /tmp/xcattables  


cd /opt/xcat/share/xcat/netboot/centos
ln -s ../rh/dracut_033 .
ln -s ../rh/dracut .

cd /
cat /tmp/trinity/controller/xcat/patches/*.patch | patch -p0
systemctl restart xcatd
systemctl enable ntpd
systemctl start ntpd
makedhcp -n
makehosts -n
makedns -n

#--------------------------------------------------------------------------------------
# correct any network settings
#--------------------------------------------------------------------------------------

# setup NAT, so nodes can access the internet (see manual step 1.f)
yum -y install iptables-services
chkconfig iptables on
service iptables start
modprobe iptable_nat
iptables -A FORWARD -i $ETH2 -j ACCEPT
iptables -t nat -A POSTROUTING -o $ETH1 -j MASQUERADE
iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited
service iptables save

#--------------------------------------------------------------------------------------
# setup routing for the virtual clusters
#--------------------------------------------------------------------------------------
ip route add 172.16.0.0/12 dev $ETH2
cat << END > /etc/sysconfig/network-scripts/route-$ETH2 
ADDRESS0=172.16.0.0
NETMASK0=255.240.0.0
END

#--------------------------------------------------------------------------------------
# Start opensm on the controller
#--------------------------------------------------------------------------------------
yum -y groupinstall "Infiniband Support"
yum -y install opensm
yum -y install infiniband-diags

systemctl enable opensm
systemctl start opensm


#--------------------------------------------------------------------------------------
# now setup NFS
#--------------------------------------------------------------------------------------
yum -y install nfs-utils nfs-utils-lib
systemctl enable nfs-server
systemctl start nfs-server

cat << END > /etc/exports 
/tftpboot *(rw,no_root_squash,sync,no_subtree_check)
/install *(rw,no_root_squash,sync,no_subtree_check)
/trinity *(rw,sync,no_root_squash,no_all_squash)
/cluster *(rw,sync,no_root_squash,no_all_squash)
/home *(rw,sync,no_root_squash,no_all_squash)
END

mkdir /cluster
exportfs -a

#--------------------------------------------------------------------------------------
# Create installation tree
#--------------------------------------------------------------------------------------
echo "Creating installation tree"
# updates and extras are required to install docker
reposync -n -r updates -r extras -p /install/post/otherpkgs/centos7.0/x86_64/
copycds -o -n centos7.0 /tmp/trinity/iso/$(ls -cr /tmp/trinity/iso/*.iso | head -1)
# copy openvswitch
mkdir -p /install/post/otherpkgs/centos7.0/x86_64/openstack
yum -y install https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-4.noarch.rpm
yum -y install --downloadonly --downloaddir=/install/post/otherpkgs/centos7.0/x86_64/openstack openvswitch
# now bundle into a repository
createrepo /install/post/otherpkgs/centos7.0/x86_64/
# generate the image
genimage centos7.0-x86_64-netboot-trinity
packimage centos7.0-x86_64-netboot-trinity

#---------------------------------------------------------------------------------------
# Workaround: create a default munge key for vc-a cluster
#---------------------------------------------------------------------------------------
dd if=/dev/urandom bs=1 count=1024 >/cluster/vc-a/etc/munge/munge.key
chmod 400 /cluster/vc-a/etc/munge/munge.key
chown 1002:1002 /cluster/vc-a/etc/munge/munge.key

echo "xcat installed" >> /var/log/postinstall.log
#--------------------------------------------------------------------------------------
# cleanup
#--------------------------------------------------------------------------------------

#umount /tmp/trinity
#rmdir /tmp/trinity

exit 0

