#!/usr/bin/bash

ips=$(tail /var/log/messages | grep discovery | awk -F' ' '{print $11}' | sort -u)
for ip in $ips; do
    mac=$(arp $ip | tail -1 | awk -F' ' '{print $3}')
    decimal=$(python -c "print '.'.join([str(int(c,16)) for c in '$mac'.split(':')])")
    port=$(snmpwalk -v2c -c public switch .1.3.6.1.2.1.17.7.1.2.2.1.2 | grep $decimal | awk -F' ' '{print $4'})
    name=$(snmpwalk -v2c -c public switch .1.3.6.1.2.1.31.1.1.1.1 | grep "IF-MIB::ifName.$port = STRING:" | cut -d' ' -f 4-)
    echo node $ip mac $mac is attached to port $port \"$name\"
done

